const cssnano = require("cssnano");
const postcssSorting = require("postcss-sorting");
const autoprefixer = require("autoprefixer");
const postcssImport = require("postcss-import");

module.exports = {
    plugins: [
        postcssImport({}),
        autoprefixer({}),
        postcssSorting({
            order: [
                "custom-properties",
                "dollar-variables",
                "declarations",
                "rules",
                "at-rules",
            ],
            "properties-order": [
                "position",
                "z-index",
                "top",
                "right",
                "bottom",
                "left",
                "display",
                "visibility",
                "flex",
                "flex-grow",
                "flex-shrink",
                "flex-basis",
                "flex-direction",
                "flex-wrap",
                "justify-content",
                "align-items",
                "align-content",
                "order",
                "overflow",
                "overflow-x",
                "overflow-y",
                "box-sizing",
                "width",
                "min-width",
                "max-width",
                "height",
                "min-height",
                "max-height",
                "padding",
                "padding-top",
                "padding-right",
                "padding-bottom",
                "padding-left",
                "border",
                "border-top",
                "border-right",
                "border-bottom",
                "border-left",
                "border-width",
                "border-top-width",
                "border-right-width",
                "border-bottom-width",
                "border-left-width",
                "border-style",
                "border-top-style",
                "border-right-style",
                "border-bottom-style",
                "border-left-style",
                "border-color",
                "border-top-color",
                "border-right-color",
                "border-bottom-color",
                "border-left-color",
                "border-radius",
                "border-top-left-radius",
                "border-top-right-radius",
                "border-bottom-right-radius",
                "border-bottom-left-radius",
                "outline",
                "outline-width",
                "outline-style",
                "outline-color",
                "outline-offset",
                "box-shadow",
                "margin",
                "margin-top",
                "margin-right",
                "margin-bottom",
                "margin-left",
                "background",
                "background-color",
                "color",
                "font",
                "font-family",
                "font-size",
                "font-weight",
                "font-style",
                "line-height",
                "text-align",
                "text-transform",
                "text-decoration",
                "text-overflow",
                "white-space",
                "word-wrap",
            ],
            "unspecified-properties-position": "bottomAlphabetical",
        }),
        cssnano({
            preset: "default",
        }),
    ],
};
